const fs = require('fs').promises;
const path = require('path');
const archiver = require('archiver');
const { generateBackend, createZip: createBackendZip, cleanup } = require('./backendGenerator');
const { generateFrontend } = require('./frontendGenerator');

/**
 * Full Stack Generator for Griffion
 * 
 * Generates both backend and frontend in a single project structure:
 * project-{timestamp}/
 *   backend/
 *   frontend/
 *   README.md
 */

/**
 * Generate complete full-stack project
 */
async function generateFullStack(config) {
  console.log('🚀 Starting Griffion Full-Stack generation...');
  console.log('📋 Configuration:', JSON.stringify(config, null, 2));
  
  const backendRoot = path.join(__dirname, '../..');
  const projectDir = path.join(backendRoot, 'temp', `project-${Date.now()}`);
  
  try {
    // Create project root directory
    await fs.mkdir(projectDir, { recursive: true });
    console.log(`📁 Created project directory: ${projectDir}`);
    
    // Step 1: Generate Backend
    console.log('\n🔧 Step 1: Generating Backend...\n');
    const backendTempDir = await generateBackend(config);
    
    // Move backend to project/backend
    const backendDir = path.join(projectDir, 'backend');
    await fs.rename(backendTempDir, backendDir);
    console.log(`✅ Backend moved to: ${backendDir}`);
    
    // Step 2: Generate Frontend
    console.log('\n🎨 Step 2: Generating Frontend...\n');
    
    // Prepare frontend config
    const frontendConfig = {
      projectName: config.projectName || 'griffion-app',
      appName: config.projectName || 'Griffion App',
      apiUrl: config.frontendApiUrl || 'http://localhost:5000',
      defaultTheme: config.defaultTheme || 'dark',
      defaultRole: config.defaultRole || 'User',
      primaryColor: config.primaryColor || '#6366f1',
      secondaryColor: config.secondaryColor || '#8b5cf6',
      logoPath: config.logoPath || '/logo.png',
      primaryIdentifier: config.primaryIdentifier || 'email',
      selfRegisterRoles: config.selfRegisterRoles || 'user,buyer,seller',
      author: config.author
    };
    
    const frontendTempDir = await generateFrontend(frontendConfig);
    
    // Move frontend to project/frontend
    const frontendDir = path.join(projectDir, 'frontend');
    await fs.rename(frontendTempDir, frontendDir);
    console.log(`✅ Frontend moved to: ${frontendDir}`);
    
    // Step 3: Create project-level README
    console.log('\n📚 Step 3: Creating project documentation...');
    await createProjectReadme(projectDir, config);
    console.log('✅ Project README created');
    
    // Step 4: Create docker-compose for easy deployment
    console.log('\n🐳 Step 4: Creating Docker Compose configuration...');
    await createDockerCompose(projectDir, config);
    console.log('✅ Docker Compose created');
    
    console.log('\n✅ Full-Stack generation completed successfully!');
    console.log(`📦 Project location: ${projectDir}`);
    console.log('\n💡 Customer setup:');
    console.log('   1. Extract the ZIP file');
    console.log('   2. cd backend && npm install && npx prisma db push');
    console.log('   3. cd ../frontend && npm install');
    console.log('   4. Start backend: cd backend && npm start');
    console.log('   5. Start frontend: cd frontend && npm run dev');
    console.log('   OR use Docker: docker-compose up');
    
    return projectDir;
    
  } catch (error) {
    console.error('❌ Full-Stack generation failed:', error);
    
    // Cleanup on failure
    try {
      await fs.rm(projectDir, { recursive: true, force: true });
    } catch (cleanupError) {
      console.error('Failed to cleanup:', cleanupError);
    }
    
    throw error;
  }
}

/**
 * Create project-level README
 */
async function createProjectReadme(projectDir, config) {
  const appName = config.projectName || 'Griffion Application';
  const apiUrl = config.frontendApiUrl || 'http://localhost:5000';
  
  const readmeContent = `# ${appName}

Full-stack application generated by Griffion with Next.js frontend and Node.js backend.

## 🚀 Quick Start

### Option 1: Manual Setup (Recommended for Development)

#### Backend Setup

\`\`\`bash
cd backend
npm install
npx prisma db push
npm start
\`\`\`

Backend will run on http://localhost:5000

**Default Admin Credentials:**
- Email: \`admin@test.local\`
- Password: \`TestAdmin123!\`
- ⚠️ Change these immediately in production!

#### Frontend Setup

\`\`\`bash
cd frontend
npm install
npm run dev
\`\`\`

Frontend will run on http://localhost:3000

### Option 2: Docker Compose (One Command)

\`\`\`bash
docker-compose up
\`\`\`

- Backend: http://localhost:5000
- Frontend: http://localhost:3000
- PostgreSQL: localhost:5432

## 📁 Project Structure

\`\`\`
${appName}/
├── backend/                 # Node.js + Express + Prisma
│   ├── src/
│   │   ├── routes/         # API routes
│   │   ├── controllers/    # Business logic
│   │   ├── middleware/     # Auth, validation, etc.
│   │   ├── database/       # Database initialization
│   │   └── utils/          # Utilities
│   ├── prisma/
│   │   └── schema.prisma   # Database schema
│   ├── .env                # Backend configuration
│   ├── package.json
│   └── README.md
│
├── frontend/               # Next.js + TypeScript + Redux
│   ├── app/               # Next.js App Router
│   │   ├── login/
│   │   ├── register/
│   │   ├── (dashboard)/
│   │   └── [role]/
│   ├── components/        # React components
│   ├── lib/              # API client, Redux, utilities
│   ├── .env.local        # Frontend configuration
│   ├── package.json
│   └── README.md
│
├── docker-compose.yml     # Docker orchestration
└── README.md             # This file
\`\`\`

## 🔧 Configuration

### Backend (.env in backend/)

\`\`\`env
PORT=5000
DATABASE_URL=file:./dev.db
JWT_SECRET=your-secret-here
JWT_REFRESH_SECRET=your-refresh-secret-here
FRONTEND_URL=http://localhost:3000
\`\`\`

### Frontend (.env.local in frontend/)

\`\`\`env
NEXT_PUBLIC_API_URL=${apiUrl}
NEXT_PUBLIC_DEFAULT_THEME=dark
NEXT_PUBLIC_APP_NAME=${appName}
\`\`\`

## 🎨 Features

### Backend
- ✅ JWT Authentication with refresh tokens
- ✅ Role-based access control (RBAC)
- ✅ User management
- ✅ 2FA support (TOTP)
- ✅ Password recovery
- ✅ Audit logging
- ✅ Dynamic navigation
- ✅ Email notifications
- ✅ Rate limiting
- ✅ RESTful API

### Frontend
- ✅ Next.js 16 with App Router
- ✅ TypeScript
- ✅ Redux Toolkit state management
- ✅ Responsive design (mobile-first)
- ✅ Dark/Light theme
- ✅ Authentication flows
- ✅ Role-based navigation
- ✅ Protected routes
- ✅ Token auto-refresh
- ✅ Form validation

## 📖 Documentation

### Backend Documentation
- \`backend/README.md\` - Backend setup and API
- \`backend/docs/API-GUIDE.md\` - Complete API reference
- \`backend/docs/CONFIG-GUIDE.md\` - Configuration options
- \`backend/GRIFFION_API.postman_collection.json\` - Postman collection

### Frontend Documentation
- \`frontend/README.md\` - Frontend setup
- \`frontend/API_INTEGRATION_GUIDE.md\` - API integration
- \`frontend/REDUX_IMPLEMENTATION.md\` - State management
- \`frontend/QUICK_START.md\` - Getting started

## 🚢 Deployment

### Development
\`\`\`bash
# Terminal 1: Backend
cd backend && npm start

# Terminal 2: Frontend
cd frontend && npm run dev
\`\`\`

### Production

#### Backend
\`\`\`bash
cd backend
npm install --production
npx prisma generate
npx prisma db push
npm start
\`\`\`

#### Frontend
\`\`\`bash
cd frontend
npm install
npm run build
npm start
\`\`\`

### Docker (Production)
\`\`\`bash
docker-compose -f docker-compose.prod.yml up -d
\`\`\`

## 🔐 Security

### Before Production:
1. ✅ Change default admin credentials
2. ✅ Update JWT secrets in backend/.env
3. ✅ Configure proper DATABASE_URL
4. ✅ Set strong passwords
5. ✅ Enable HTTPS
6. ✅ Configure CORS properly
7. ✅ Review rate limits
8. ✅ Enable production logging

## 🧪 Testing

### Backend
\`\`\`bash
cd backend
npm test
\`\`\`

### Frontend
\`\`\`bash
cd frontend
npm test
\`\`\`

### API Testing with Postman
1. Import \`backend/GRIFFION_API.postman_collection.json\`
2. Set base URL to http://localhost:5000
3. Login with admin credentials
4. Test all endpoints

## 🐛 Troubleshooting

### Backend won't start
- Check DATABASE_URL in .env
- Ensure port 5000 is available
- Run \`npx prisma db push\`
- Check logs in console

### Frontend can't connect to backend
- Verify NEXT_PUBLIC_API_URL in .env.local
- Ensure backend is running on port 5000
- Check CORS configuration in backend
- Clear browser cache and localStorage

### Database errors
- Delete backend/dev.db and run \`npx prisma db push\` again
- Check Prisma schema syntax
- Ensure database migrations are applied

### Authentication issues
- Clear browser localStorage
- Check JWT secrets match in backend
- Verify token expiration times
- Test with Postman first

## 📝 License

This project is generated by Griffion and ready for production use.

## 🤝 Support

For issues:
1. Check documentation in backend/docs/ and frontend/
2. Review environment configuration
3. Test API with Postman collection
4. Check logs in both backend and frontend
`;
  
  await fs.writeFile(path.join(projectDir, 'README.md'), readmeContent);
}

/**
 * Create docker-compose.yml for easy deployment
 */
async function createDockerCompose(projectDir, config) {
  const appName = (config.projectName || 'griffion-app').toLowerCase().replace(/\s+/g, '-');
  
  const dockerComposeContent = `version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ${appName}-db
    environment:
      POSTGRES_USER: griffion
      POSTGRES_PASSWORD: griffion123
      POSTGRES_DB: ${appName}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U griffion"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${appName}-backend
    environment:
      PORT: 5000
      DATABASE_URL: postgresql://griffion:griffion123@postgres:5432/${appName}
      FRONTEND_URL: http://localhost:3000
      NODE_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma db push && npm start"

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ${appName}-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
`;
  
  await fs.writeFile(path.join(projectDir, 'docker-compose.yml'), dockerComposeContent);
  
  // Also create Dockerfiles if they don't exist
  await createDockerfiles(projectDir);
}

/**
 * Create Dockerfiles for backend and frontend if they don't exist
 */
async function createDockerfiles(projectDir) {
  // Backend Dockerfile
  const backendDockerfile = `FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci --only=production

RUN npx prisma generate

COPY . .

EXPOSE 5000

CMD ["npm", "start"]
`;
  
  const backendDockerPath = path.join(projectDir, 'backend', 'Dockerfile');
  try {
    await fs.access(backendDockerPath);
  } catch {
    await fs.writeFile(backendDockerPath, backendDockerfile);
  }
  
  // Frontend Dockerfile
  const frontendDockerfile = `FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
`;
  
  const frontendDockerPath = path.join(projectDir, 'frontend', 'Dockerfile');
  try {
    await fs.access(frontendDockerPath);
  } catch {
    await fs.writeFile(frontendDockerPath, frontendDockerfile);
  }
}

/**
 * Create a ZIP archive
 */
async function createZip(sourceDir, outputPath) {
  return new Promise((resolve, reject) => {
    const output = require('fs').createWriteStream(outputPath);
    const archive = archiver('zip', { zlib: { level: 9 } });

    output.on('close', () => {
      console.log(`📦 ZIP created: ${(archive.pointer() / 1024 / 1024).toFixed(2)} MB`);
      resolve();
    });
    
    output.on('error', (err) => reject(err));
    archive.on('error', (err) => reject(err));

    archive.pipe(output);
    archive.directory(sourceDir, false);
    archive.finalize();
  });
}

module.exports = {
  generateFullStack,
  createZip,
  cleanup  // Re-exported from backendGenerator
};
